<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>SterlingTracker</AssemblyName>
    <RootNamespace>Sterling.Logistics.Tracker</RootNamespace>
    <Version>2.0.0-alpha.1</Version>
  </PropertyGroup>
</Project>
