---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sterling/sterling-web/
    - cd $DEPLOYPATH && /usr/bin/env npm install --omit=dev
    - /bin/mkdir -p $DEPLOYPATH/tmp
    - /usr/bin/touch $DEPLOYPATH/tmp/restart.txt
