import {ActionRowBuilder,AttachmentBuilder,ButtonBuilder,ButtonStyle,ChannelType,EmbedBuilder,MessageFlags,OverwriteType,PermissionFlagsBits} from "discord.js";
import {db} from "../database/mysql.js";
import {sendReviewRequest} from "../reviews/service.js";
const BRAND=0x5865f2;
const code=t=>`SL-TKT-${String(t.id).padStart(4,"0")}`;
const clean=s=>String(s||"").toLowerCase().replace(/[^a-z0-9-]/g,"-").replace(/-+/g,"-").replace(/^-|-$/g,"").slice(0,70);
const ticketName=n=>/^ticket-/i.test(n||"");
async function byOwner(id){const[r]=await db().execute("SELECT * FROM tickets WHERE owner_id=? AND status='open' ORDER BY id DESC LIMIT 1",[id]);return r[0]||null;}
async function byChannel(id){const[r]=await db().execute("SELECT * FROM tickets WHERE channel_id=? AND status IN ('open','closed_pending_delete','closed_delete_failed') ORDER BY id DESC LIMIT 1",[id]);return r[0]||null;}
async function exists(g,id){try{return!!await g.channels.fetch(id);}catch{return false;}}
export function isTicketStaff(i,c){return i.memberPermissions?.has(PermissionFlagsBits.Administrator)||i.member?.roles?.cache?.has(c.ticketStaffRoleId);}
export async function reconcileTickets(g){const[rows]=await db().query("SELECT * FROM tickets WHERE status='open' ORDER BY id DESC");let valid=0,stale=0,duplicates=0;const owners=new Set();for(const t of rows){if(owners.has(t.owner_id)){await db().execute("UPDATE tickets SET status='stale',closed_at=NOW(),close_reason='Duplicate open ticket repaired' WHERE id=?",[t.id]);duplicates++;continue;}owners.add(t.owner_id);if(await exists(g,t.channel_id))valid++;else{await db().execute("UPDATE tickets SET status='stale',closed_at=NOW(),close_reason='Discord channel no longer exists' WHERE id=?",[t.id]);stale++;}}return{valid,stale,duplicates};}
export async function postTicketPanel(i){const e=new EmbedBuilder().setTitle("🎫 Sterling Logistics Support Centre").setDescription("Welcome to Sterling Logistics Support.\n\nIf you need assistance, press **Open Ticket** below and a private support channel will be created for you.\n\n**Response**\nA member of our team will be with you as soon as possible.\n\n**Privacy**\nTickets are private between you and authorised Sterling Logistics staff.").setFooter({text:"Sterling Logistics | Driven by Excellence"}).setColor(BRAND);const row=new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("sterling_open_ticket").setLabel("Open Ticket").setEmoji("🎫").setStyle(ButtonStyle.Primary));await i.reply({embeds:[e],components:[row]});}
export async function openTicket(i,client,c){await i.deferReply({flags:MessageFlags.Ephemeral});const old=await byOwner(i.user.id);if(old){if(await exists(i.guild,old.channel_id))return i.editReply(`You already have an open Sterling Logistics support ticket: <#${old.channel_id}>`);await db().execute("UPDATE tickets SET status='stale',closed_at=NOW(),close_reason='Missing Discord channel during duplicate check' WHERE id=?",[old.id]);}const safe=clean(i.member?.displayName||i.user.globalName||i.user.username)||"member";let ch;try{ch=await i.guild.channels.create({name:`ticket-${safe}`,type:ChannelType.GuildText,parent:c.supportCategoryId,topic:`Sterling Logistics support ticket | Owner ${i.user.id}`,permissionOverwrites:[{id:i.guild.id,type:OverwriteType.Role,deny:[PermissionFlagsBits.ViewChannel]},{id:i.user.id,type:OverwriteType.Member,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory]},{id:c.ticketStaffRoleId,type:OverwriteType.Role,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory,PermissionFlagsBits.ManageMessages]},{id:client.user.id,type:OverwriteType.Member,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory,PermissionFlagsBits.ManageChannels]}]});const[r]=await db().execute("INSERT INTO tickets(channel_id,guild_id,owner_id,username,channel_name) VALUES(?,?,?,?,?)",[ch.id,i.guild.id,i.user.id,i.user.username,ch.name]);const[rows]=await db().execute("SELECT * FROM tickets WHERE id=?",[r.insertId]);const t=rows[0];const n=`ticket-${String(t.id).padStart(4,"0")}-${safe}`.slice(0,100);await ch.setName(n).catch(()=>{});await db().execute("UPDATE tickets SET channel_name=? WHERE id=?",[n,t.id]);await ch.send({content:`<@${i.user.id}> <@&${c.ticketStaffRoleId}>`,allowedMentions:{users:[i.user.id],roles:[c.ticketStaffRoleId]},embeds:[new EmbedBuilder().setTitle(`🎫 Sterling Logistics Support | ${code(t)}`).setDescription("Thanks for contacting Sterling Logistics Support.\n\n**Someone from our team will be with you soon.**\n\nPlease explain what you need help with below.").setColor(BRAND)]});return i.editReply(`🎫 **${code(t)} created successfully**\n\n<#${ch.id}>`);}catch(e){if(ch)await ch.delete("Ticket setup failed").catch(()=>{});return i.editReply(`Ticket creation failed: ${e.message}`);}}
async function need(i){const t=await byChannel(i.channelId);if(!t){await i.reply({content:"This channel is not registered as a Sterling Logistics ticket.",flags:MessageFlags.Ephemeral});return null;}return t;}
export async function handleClaim(i){const t=await need(i);if(!t)return;if(t.claimed_by&&t.claimed_by!==i.user.id)return i.reply({content:`Already claimed by <@${t.claimed_by}>`,flags:MessageFlags.Ephemeral});await db().execute("UPDATE tickets SET claimed_by=? WHERE id=?",[i.user.id,t.id]);await i.reply({content:`${code(t)} claimed.`,flags:MessageFlags.Ephemeral});}
export async function handleTicketInfo(i){const t=await need(i);if(t)await i.reply({content:`**${code(t)}**\nOwner: <@${t.owner_id}>\nClaimed: ${t.claimed_by?`<@${t.claimed_by}>`:"Nobody"}\nStatus: **${t.status}**`,flags:MessageFlags.Ephemeral});}
export async function handleAddUser(i){const t=await need(i);if(!t)return;const u=i.options.getUser("user",true);await i.channel.permissionOverwrites.edit(u.id,{ViewChannel:true,SendMessages:true,ReadMessageHistory:true});await i.reply({content:`Added <@${u.id}>.`,flags:MessageFlags.Ephemeral});}
export async function handleRemoveUser(i){const t=await need(i);if(!t)return;const u=i.options.getUser("user",true);if(u.id===t.owner_id)return i.reply({content:"You cannot remove the ticket owner.",flags:MessageFlags.Ephemeral});await i.channel.permissionOverwrites.delete(u.id);await i.reply({content:`Removed <@${u.id}>.`,flags:MessageFlags.Ephemeral});}
export async function handleRename(i){const t=await need(i);if(!t)return;const n=`ticket-${clean(i.options.getString("name",true))||"support"}`;await i.channel.setName(n);await db().execute("UPDATE tickets SET channel_name=? WHERE id=?",[n,t.id]);await i.reply({content:`Renamed to **${n}**.`,flags:MessageFlags.Ephemeral});}
async function transcript(client,c,t,ch){const dest=await client.channels.fetch(c.transcriptsChannelId);if(!dest?.isTextBased())throw new Error("Invalid transcript channel");const msgs=await ch.messages.fetch({limit:100});const lines=["STERLING LOGISTICS SUPPORT TRANSCRIPT",`Ticket: ${code(t)}`,`Owner: ${t.owner_id}`,""];for(const m of [...msgs.values()].sort((a,b)=>a.createdTimestamp-b.createdTimestamp)){lines.push(`[${m.createdAt.toISOString()}] ${m.author?.username||"Unknown"}`,m.content||"[No text]","");}await dest.send({content:`Transcript for **${code(t)}**`,files:[new AttachmentBuilder(Buffer.from(lines.join("\n")),{name:`${code(t)}-transcript.txt`})]});}
export async function handleTranscript(i,client,c){const t=await need(i);if(!t)return;await i.deferReply({flags:MessageFlags.Ephemeral});await transcript(client,c,t,i.channel);await i.editReply("Transcript saved.");}
export async function handleCloseTicket(i,client,c){const t=await need(i);if(!t)return;const reason=i.options.getString("reason")||"No reason provided";await i.deferReply({flags:MessageFlags.Ephemeral});await transcript(client,c,t,i.channel).catch(()=>{});await db().execute("UPDATE tickets SET status='closed_pending_delete',closed_at=NOW(),closed_by=?,close_reason=? WHERE id=?",[i.user.id,reason,t.id]);const[updatedRows]=await db().execute("SELECT * FROM tickets WHERE id=? LIMIT 1",[t.id]);const closedTicket=updatedRows[0]||{...t,closed_by:i.user.id};await sendReviewRequest(client,closedTicket);await i.editReply(`${code(t)} closed. A review request has been sent to the customer. This channel will now be removed.`);await new Promise(r=>setTimeout(r,700));try{await i.channel.delete(`Sterling ticket closed | ${reason}`);await db().execute("UPDATE tickets SET status='closed',discord_delete_error=NULL WHERE id=?",[t.id]);}catch(e){await db().execute("UPDATE tickets SET status='closed_delete_failed',discord_delete_error=? WHERE id=?",[String(e.message||e).slice(0,4000),t.id]);}}
export async function handleReview(i){return i.reply({content:"This review button is no longer active. Please use the review request sent to your DMs.",flags:MessageFlags.Ephemeral});}
export async function handleTicketCleanup(i){await i.deferReply({flags:MessageFlags.Ephemeral});const r=await reconcileTickets(i.guild);await i.editReply(`Cleanup complete. Valid: ${r.valid}, stale repaired: ${r.stale}, duplicates repaired: ${r.duplicates}`);}
export async function handleDeleteHiddenTickets(i,c){await i.deferReply({flags:MessageFlags.Ephemeral});const[rows]=await db().query("SELECT channel_id FROM tickets WHERE status='open'");const valid=new Set(rows.map(r=>r.channel_id));const children=i.guild.channels.cache.filter(ch=>ch.parentId===c.supportCategoryId&&ch.type===ChannelType.GuildText);let del=0,keep=0,fail=0;for(const ch of children.values()){if(!ticketName(ch.name))continue;if(valid.has(ch.id)){keep++;continue;}try{await ch.delete("Sterling orphan cleanup");del++;}catch{fail++;}}await i.editReply(`Orphan cleanup complete. Deleted: ${del}, kept: ${keep}, failed: ${fail}`);}
export async function handleManualChannelDelete(ch){try{await db().execute("UPDATE tickets SET status='stale',closed_at=COALESCE(closed_at,NOW()),close_reason=COALESCE(close_reason,'Discord channel deleted manually') WHERE channel_id=? AND status='open'",[ch.id]);}catch{}}
