<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>SterlingTracker</AssemblyName>
    <RootNamespace>SterlingTracker</RootNamespace>
    <Version>3.0.6</Version>
    <AssemblyVersion>3.0.6.0</AssemblyVersion>
    <FileVersion>3.0.6.0</FileVersion>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
  </PropertyGroup>
</Project>
