import mysql from "mysql2/promise";let pool;export function initDatabase(c){pool=mysql.createPool({host:c.host,port:c.port,database:c.database,user:c.user,password:c.password,waitForConnections:true,connectionLimit:10,queueLimit:0,enableKeepAlive:true});}export function db(){if(!pool)throw new Error("Database not initialized");return pool;}export async function pingDatabase(){const[rows]=await db().query("SELECT DATABASE() db, CURRENT_USER() username");return rows[0];}
export async function ensureSchema(){const sql=[
`CREATE TABLE IF NOT EXISTS tickets(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,channel_id VARCHAR(32) NOT NULL UNIQUE,guild_id VARCHAR(32) NOT NULL,owner_id VARCHAR(32) NOT NULL,username VARCHAR(100),channel_name VARCHAR(100),ticket_type VARCHAR(50) NOT NULL DEFAULT 'general',claimed_by VARCHAR(32),created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,closed_at TIMESTAMP NULL,closed_by VARCHAR(32),close_reason VARCHAR(500),status VARCHAR(50) NOT NULL DEFAULT 'open',review_rating TINYINT UNSIGNED,reviewed_at TIMESTAMP NULL,discord_delete_error TEXT,INDEX(owner_id,status))`,
`CREATE TABLE IF NOT EXISTS ticket_reviews(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,ticket_id BIGINT UNSIGNED NOT NULL UNIQUE,reviewer_discord_id VARCHAR(32) NOT NULL,staff_discord_id VARCHAR(32),rating TINYINT UNSIGNED NOT NULL,review_text VARCHAR(1000),created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX(staff_discord_id,created_at),INDEX(rating,created_at))`,
`CREATE TABLE IF NOT EXISTS drivers(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,sterling_driver_id VARCHAR(20) UNIQUE,discord_id VARCHAR(32) NOT NULL UNIQUE,discord_username VARCHAR(100),truckersmp_id VARCHAR(32),steam_id VARCHAR(32),country VARCHAR(100),timezone VARCHAR(100),rank_name VARCHAR(100) NOT NULL DEFAULT 'Trainee Driver',department VARCHAR(100),joined_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,left_at TIMESTAMP NULL,status VARCHAR(50) NOT NULL DEFAULT 'active',total_miles DECIMAL(14,2) NOT NULL DEFAULT 0,monthly_miles DECIMAL(14,2) NOT NULL DEFAULT 0,jobs_completed INT UNSIGNED NOT NULL DEFAULT 0,total_income DECIMAL(16,2) NOT NULL DEFAULT 0,convoys_attended INT UNSIGNED NOT NULL DEFAULT 0,attendance_percent DECIMAL(5,2) NOT NULL DEFAULT 0,safety_score DECIMAL(6,2) NOT NULL DEFAULT 100)`,
`CREATE TABLE IF NOT EXISTS applications(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,application_code VARCHAR(20) UNIQUE,discord_id VARCHAR(32) NOT NULL,country VARCHAR(100),timezone VARCHAR(100),ets2_experience TEXT,truckersmp_id VARCHAR(32),previous_vtc TEXT,availability TEXT,motivation TEXT,agreed_rules TINYINT(1) NOT NULL DEFAULT 0,status VARCHAR(50) NOT NULL DEFAULT 'pending',reviewer_id VARCHAR(32),reviewer_notes TEXT,decision_reason TEXT,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,decided_at TIMESTAMP NULL)`,
`CREATE TABLE IF NOT EXISTS hr_cases(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,case_code VARCHAR(20) UNIQUE,driver_id BIGINT UNSIGNED NOT NULL,staff_discord_id VARCHAR(32) NOT NULL,case_type VARCHAR(50) NOT NULL,reason TEXT,evidence TEXT,action_taken TEXT,notes TEXT,appeal_status VARCHAR(50) NOT NULL DEFAULT 'none',created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
`CREATE TABLE IF NOT EXISTS loa_requests(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,driver_id BIGINT UNSIGNED NOT NULL,start_date DATE NOT NULL,expected_return_date DATE NOT NULL,reason TEXT,status VARCHAR(50) NOT NULL DEFAULT 'pending',reviewer_id VARCHAR(32),decision_at TIMESTAMP NULL,returned_at TIMESTAMP NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
`CREATE TABLE IF NOT EXISTS training_records(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,driver_id BIGINT UNSIGNED NOT NULL,trainer_discord_id VARCHAR(32) NOT NULL,module_name VARCHAR(150) NOT NULL,result VARCHAR(50) NOT NULL,notes TEXT,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
`CREATE TABLE IF NOT EXISTS convoys(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,convoy_code VARCHAR(20) UNIQUE,name VARCHAR(150) NOT NULL,game VARCHAR(50) NOT NULL DEFAULT 'ETS2',server_name VARCHAR(150),event_date DATE NOT NULL,meetup_time VARCHAR(20),departure_time VARCHAR(20),departure_city VARCHAR(150),destination VARCHAR(150),route_text TEXT,dlc_requirements TEXT,truck_requirements TEXT,notes TEXT,created_by VARCHAR(32) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
`CREATE TABLE IF NOT EXISTS jobs(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,job_code VARCHAR(30) UNIQUE,driver_id BIGINT UNSIGNED NOT NULL,truck_brand VARCHAR(100),truck_model VARCHAR(100),trailer VARCHAR(150),cargo VARCHAR(150),cargo_weight_kg DECIMAL(12,2),origin_city VARCHAR(150),destination_city VARCHAR(150),distance_miles DECIMAL(12,2),real_duration_seconds INT UNSIGNED,game_duration_minutes INT UNSIGNED,income DECIMAL(16,2),fuel_used_liters DECIMAL(12,2),truck_damage DECIMAL(8,4),trailer_damage DECIMAL(8,4),cargo_damage DECIMAL(8,4),max_speed_mph DECIMAL(8,2),status VARCHAR(50) NOT NULL DEFAULT 'completed',started_at TIMESTAMP NULL,completed_at TIMESTAMP NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
`CREATE TABLE IF NOT EXISTS telemetry_sessions(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,session_code VARCHAR(40) UNIQUE,driver_id BIGINT UNSIGNED NOT NULL,status VARCHAR(50) NOT NULL DEFAULT 'online',last_seen_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,ended_at TIMESTAMP NULL)`,
`CREATE TABLE IF NOT EXISTS telemetry_events(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,session_id BIGINT UNSIGNED NOT NULL,driver_id BIGINT UNSIGNED NOT NULL,event_type VARCHAR(80) NOT NULL,direct_event TINYINT(1) NOT NULL DEFAULT 0,event_json JSON NOT NULL,occurred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
`CREATE TABLE IF NOT EXISTS promotions(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,driver_id BIGINT UNSIGNED NOT NULL,old_rank VARCHAR(100),new_rank VARCHAR(100) NOT NULL,promoted_by VARCHAR(32) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX(driver_id,created_at))`,
`CREATE TABLE IF NOT EXISTS achievements(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,driver_id BIGINT UNSIGNED NOT NULL,name VARCHAR(150) NOT NULL,description VARCHAR(500),awarded_by VARCHAR(32) NOT NULL,awarded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX(driver_id,awarded_at))`,
`CREATE TABLE IF NOT EXISTS audit_logs(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,actor_discord_id VARCHAR(32) NOT NULL,action VARCHAR(100) NOT NULL,target_discord_id VARCHAR(32),details TEXT,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX(actor_discord_id,created_at),INDEX(action,created_at))`];for(const q of sql)await db().query(q);}
