import {Client,Events,EmbedBuilder,MessageFlags,PermissionFlagsBits,REST,Routes,SlashCommandBuilder} from "discord.js";
import {loadConfig} from "../config.js";
import {db} from "../database/mysql.js";

const admin=PermissionFlagsBits.Administrator;
const money=v=>`£${Number(v||0).toLocaleString("en-GB",{minimumFractionDigits:2,maximumFractionDigits:2})}`;

async function driverByDiscord(id){const[r]=await db().execute("SELECT * FROM drivers WHERE discord_id=? LIMIT 1",[id]);return r[0]||null;}
async function nextDriverJobNumber(driverId){const[r]=await db().execute("SELECT COUNT(*) n FROM jobs WHERE driver_id=?",[driverId]);return Number(r[0]?.n||0)+1;}
function displayRef(driver,n){const id=String(driver.sterling_driver_id||`Driver ${driver.id}`).replace(/^SL[- ]?/i,"Driver ");return `${id} — Job ${String(n).padStart(3,"0")}`;}
function commands(){return[
 new SlashCommandBuilder().setName("driverjobs").setDescription("Show a driver's recent Sterling jobs").addUserOption(o=>o.setName("driver").setDescription("Driver to view").setRequired(false)),
 new SlashCommandBuilder().setName("jobadd").setDescription("Staff: manually add a completed driver job").setDefaultMemberPermissions(admin)
  .addUserOption(o=>o.setName("driver").setDescription("Driver").setRequired(true))
  .addStringOption(o=>o.setName("origin").setDescription("Origin city").setRequired(true).setMaxLength(150))
  .addStringOption(o=>o.setName("destination").setDescription("Destination city").setRequired(true).setMaxLength(150))
  .addStringOption(o=>o.setName("cargo").setDescription("Cargo").setRequired(true).setMaxLength(150))
  .addNumberOption(o=>o.setName("miles").setDescription("Miles").setRequired(true).setMinValue(0.1).setMaxValue(10000))
  .addNumberOption(o=>o.setName("income").setDescription("Job revenue").setRequired(false).setMinValue(0).setMaxValue(1000000000))
  .addBooleanOption(o=>o.setName("pay_driver").setDescription("Queue this for payment review? Default false").setRequired(false))
].map(x=>x.toJSON());}
async function register(){const c=loadConfig(),rest=new REST({version:"10"}).setToken(c.token),route=Routes.applicationGuildCommands(c.applicationId,c.guildId),existing=await rest.get(route);for(const body of commands()){const old=existing.find(x=>x.name===body.name);if(old)await rest.patch(Routes.applicationGuildCommand(c.applicationId,c.guildId,old.id),{body});else await rest.post(route,{body});}console.log("[Driver History] commands registered");}
async function history(i){const user=i.options.getUser("driver")||i.user,d=await driverByDiscord(user.id);if(!d)return i.reply({content:"No Sterling driver profile found.",flags:MessageFlags.Ephemeral});const[r]=await db().execute(`SELECT id,job_code,origin_city,destination_city,cargo,distance_miles,income,status,submission_source,completed_at,created_at FROM jobs WHERE driver_id=? ORDER BY COALESCE(completed_at,created_at) DESC,id DESC LIMIT 15`,[d.id]);const rows=r;const text=rows.length?rows.map((x,idx)=>`**${displayRef(d,Math.max(1,Number(x.id)))}**${x.job_code?` • \`${x.job_code}\``:""}\n${x.origin_city||"?"} → ${x.destination_city||"?"} • ${x.cargo||"Unknown"} • ${Number(x.distance_miles||0).toFixed(1)} mi • ${money(x.income)}\n${String(x.status||"unknown").replaceAll("_"," ")} • ${x.submission_source||"tracker"}`).join("\n\n"):"No jobs recorded yet.";return i.reply({embeds:[new EmbedBuilder().setTitle(`Driver Job History • ${d.sterling_driver_id||user.username}`).setDescription(text.slice(0,3900)).setFooter({text:"Tracker and manual jobs are both shown"})]});}
async function add(i){const user=i.options.getUser("driver",true),d=await driverByDiscord(user.id);if(!d)return i.reply({content:"No Sterling driver profile found for that user.",flags:MessageFlags.Ephemeral});const n=await nextDriverJobNumber(d.id),ref=displayRef(d,n),origin=i.options.getString("origin",true),destination=i.options.getString("destination",true),cargo=i.options.getString("cargo",true),miles=i.options.getNumber("miles",true),income=i.options.getNumber("income")||0,pay=i.options.getBoolean("pay_driver")||false;const status=pay?"pending_review":"completed";const[r]=await db().execute(`INSERT INTO jobs(driver_id,job_code,origin_city,destination_city,cargo,distance_miles,income,status,started_at,completed_at,submission_source,submitted_by,manual_submitted_at) VALUES(?,?,?,?,?,?,?,?,NOW(),NOW(),'manual',?,NOW())`,[d.id,`STAFF-${Date.now().toString(36).toUpperCase()}`,origin,destination,cargo,miles,income,status,i.user.id]);if(!pay)await db().execute("UPDATE drivers SET total_miles=total_miles+?,monthly_miles=monthly_miles+?,jobs_completed=jobs_completed+1 WHERE id=?",[miles,miles,d.id]);try{await db().execute("INSERT INTO audit_logs(actor_discord_id,action,target_discord_id,details) VALUES(?,?,?,?)",[i.user.id,"job.staff.add",user.id,`${ref} | ${origin} -> ${destination} | ${miles} mi | pay=${pay}`]);}catch{}return i.reply({embeds:[new EmbedBuilder().setTitle(`✅ ${ref}`).setDescription(`Manual staff job added for <@${user.id}>.`).addFields({name:"Route",value:`${origin} → ${destination}`},{name:"Cargo",value:cargo,inline:true},{name:"Miles",value:Number(miles).toFixed(1),inline:true},{name:"Revenue",value:money(income),inline:true},{name:"Payment",value:pay?"Pending staff approval/payment":"No automatic payment"})],flags:MessageFlags.Ephemeral});}
async function handle(i){if(!i.isChatInputCommand())return;if(i.commandName==="driverjobs")return history(i);if(i.commandName==="jobadd")return add(i);}
const original=Client.prototype.login;if(!Client.prototype.__sterlingDriverHistory){Object.defineProperty(Client.prototype,"__sterlingDriverHistory",{value:true});Client.prototype.login=function(...args){if(!this.__sterlingDriverHistoryRuntime){Object.defineProperty(this,"__sterlingDriverHistoryRuntime",{value:true});this.on(Events.InteractionCreate,i=>handle(i).catch(e=>console.error("[Driver History]",e)));this.once(Events.ClientReady,()=>{setTimeout(()=>register().catch(e=>console.error("[Driver History] registration",e)),15000);});}return original.apply(this,args);};}
