const pro=document.createElement('link');pro.rel='stylesheet';pro.href='/pro.css?v=1';document.head.appendChild(pro);
const $=s=>document.querySelector(s),fmt=n=>Number(n||0).toLocaleString(undefined,{maximumFractionDigits:0}),money=n=>`£${Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
let signedIn=false,loading=false;
async function load(){
  if(loading)return;loading=true;
  try{
    const r=await fetch('/api/web/me',{headers:{Accept:'application/json'},cache:'no-store'});if(r.status===401){$('#login-state').classList.remove('hidden');$('#dashboard').classList.add('hidden');signedIn=false;return}if(!r.ok){if(!signedIn){$('#login-state').classList.remove('hidden');$('#login-state p').textContent='Your dashboard could not be loaded right now.'}return}
    const d=await r.json(),x=d.driver,live=d.live;signedIn=true;$('#login-state').classList.add('hidden');$('#dashboard').classList.remove('hidden');
    $('#driver-name').textContent=x.name||'Sterling Driver';$('#driver-id').textContent=x.sterlingDriverId||'—';$('#driver-rank').textContent=x.rank||'Driver';$('#avatar').src=x.avatar||'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="64" height="64"%3E%3Crect width="64" height="64" fill="%23172839"/%3E%3Ctext x="32" y="40" text-anchor="middle" font-size="24" fill="%23ff9b29"%3ES%3C/text%3E%3C/svg%3E';
    const online=live&&live.status!=='offline'&&Date.now()-new Date(live.lastSeenAt).getTime()<120000;$('#driver-status').textContent=online?'● LIVE TRACKER':'OFFLINE';
    $('#drive-score').textContent=`${Math.round(x.driveScore?.score||0)}/100`;$('#jobs-count').textContent=fmt(x.jobsCompleted);$('#miles-total').textContent=fmt(x.totalMiles);$('#earnings-total').textContent=money(x.economy?.totalEarned);$('#monthly-miles').textContent=fmt(x.monthlyMiles);$('#wallet').textContent=money(x.economy?.balance);
    if(live){$('#current-route').textContent=live.origin||live.destination?`${live.origin||'?'} → ${live.destination||'?'}`:'No active route';$('#live-truck').textContent=live.truck||'—';$('#live-cargo').textContent=live.cargo||'—';$('#live-speed').textContent=`${Math.round(live.speedMph||0)} mph`;$('#live-revenue').textContent=money(live.revenue)}else{$('#current-route').textContent='Tracker offline';$('#live-truck').textContent='—';$('#live-cargo').textContent='—';$('#live-speed').textContent='0 mph';$('#live-revenue').textContent=money(0)}
    $('#jobs-body').innerHTML=d.jobs.length?d.jobs.map(j=>`<tr><td>${new Date(j.completed_at||j.created_at).toLocaleDateString()}</td><td>${esc(j.cargo||'—')}</td><td>${esc(j.origin_city||'?')} → ${esc(j.destination_city||'?')}</td><td>${Number(j.distance_miles||0).toFixed(0)} mi</td><td>${money(j.income)}</td></tr>`).join(''):'<tr><td colspan="5">No completed jobs recorded yet.</td></tr>';
    $('#achievements').innerHTML=d.achievements.length?d.achievements.map(a=>`<div class="activity-item"><div class="activity-icon">★</div><div><b>${esc(a.name)}</b><span>${esc(a.description||'Sterling achievement')}</span></div></div>`).join(''):'<div class="activity-item"><div><b>No achievements yet</b><span>Your Sterling milestones will appear here.</span></div></div>';
  }finally{loading=false}
}
$('#logout').addEventListener('click',async()=>{await fetch('/auth/web/logout',{method:'POST'});location.href='/'});load();setInterval(()=>{if(signedIn&&!document.hidden)load()},2000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)load()});
