import {PermissionFlagsBits,REST,Routes,SlashCommandBuilder} from "discord.js";
export function commandData(){return[
new SlashCommandBuilder().setName("setupverify").setDescription("Post verification panel").setDefaultMemberPermissions(PermissionFlagsBits.Administrator),
new SlashCommandBuilder().setName("setuptickets").setDescription("Post support panel").setDefaultMemberPermissions(PermissionFlagsBits.Administrator),
new SlashCommandBuilder().setName("claim").setDescription("Claim current ticket"),
new SlashCommandBuilder().setName("ticketinfo").setDescription("View ticket info"),
new SlashCommandBuilder().setName("adduser").setDescription("Add member to ticket").addUserOption(o=>o.setName("user").setDescription("Member").setRequired(true)),
new SlashCommandBuilder().setName("removeuser").setDescription("Remove member from ticket").addUserOption(o=>o.setName("user").setDescription("Member").setRequired(true)),
new SlashCommandBuilder().setName("rename").setDescription("Rename ticket").addStringOption(o=>o.setName("name").setDescription("Name").setRequired(true)),
new SlashCommandBuilder().setName("transcript").setDescription("Save ticket transcript"),
new SlashCommandBuilder().setName("closeticket").setDescription("Close ticket").addStringOption(o=>o.setName("reason").setDescription("Reason").setRequired(false)),
new SlashCommandBuilder().setName("ticketcleanup").setDescription("Repair stale/duplicate ticket records").setDefaultMemberPermissions(PermissionFlagsBits.Administrator),
new SlashCommandBuilder().setName("deletehiddentickets").setDescription("Delete orphan ticket channels").setDefaultMemberPermissions(PermissionFlagsBits.Administrator),
new SlashCommandBuilder().setName("profile").setDescription("View driver profile").addUserOption(o=>o.setName("user").setDescription("Driver").setRequired(false)),
new SlashCommandBuilder().setName("jobs").setDescription("View recent jobs").addUserOption(o=>o.setName("user").setDescription("Driver").setRequired(false)),
new SlashCommandBuilder().setName("leaderboard").setDescription("View Sterling Logistics driver leaderboard").addStringOption(o=>o.setName("metric").setDescription("Leaderboard metric").setRequired(false).addChoices({name:"Monthly Miles",value:"monthly"},{name:"Total Miles",value:"total"},{name:"Jobs Completed",value:"jobs"},{name:"Safety Score",value:"safety"})),
new SlashCommandBuilder().setName("companystats").setDescription("View Sterling Logistics company statistics"),
new SlashCommandBuilder().setName("achievements").setDescription("View driver achievements").addUserOption(o=>o.setName("user").setDescription("Driver").setRequired(false)),
new SlashCommandBuilder().setName("achievementgive").setDescription("Award an achievement to a driver").setDefaultMemberPermissions(PermissionFlagsBits.Administrator).addUserOption(o=>o.setName("user").setDescription("Driver").setRequired(true)).addStringOption(o=>o.setName("name").setDescription("Achievement name").setRequired(true)).addStringOption(o=>o.setName("description").setDescription("Description").setRequired(false)),
new SlashCommandBuilder().setName("driveradmin").setDescription("Manage a Sterling driver").setDefaultMemberPermissions(PermissionFlagsBits.Administrator)
.addSubcommand(s=>s.setName("setrank").setDescription("Change driver rank").addUserOption(o=>o.setName("user").setDescription("Driver").setRequired(true)).addStringOption(o=>o.setName("rank").setDescription("New rank").setRequired(true)))
.addSubcommand(s=>s.setName("setstatus").setDescription("Change driver status").addUserOption(o=>o.setName("user").setDescription("Driver").setRequired(true)).addStringOption(o=>o.setName("status").setDescription("Status").setRequired(true).addChoices({name:"Active",value:"active"},{name:"LOA",value:"loa"},{name:"Suspended",value:"suspended"},{name:"Left",value:"left"})))
.addSubcommand(s=>s.setName("addmiles").setDescription("Add manual miles").addUserOption(o=>o.setName("user").setDescription("Driver").setRequired(true)).addNumberOption(o=>o.setName("miles").setDescription("Miles to add").setRequired(true).setMinValue(0.1))),
new SlashCommandBuilder().setName("apply").setDescription("Apply to Sterling Logistics"),
new SlashCommandBuilder().setName("application").setDescription("Manage application").setDefaultMemberPermissions(PermissionFlagsBits.Administrator).addSubcommand(s=>s.setName("accept").setDescription("Accept").addIntegerOption(o=>o.setName("application").setDescription("Application ID").setRequired(true)).addStringOption(o=>o.setName("reason").setDescription("Notes").setRequired(false))).addSubcommand(s=>s.setName("reject").setDescription("Reject").addIntegerOption(o=>o.setName("application").setDescription("Application ID").setRequired(true)).addStringOption(o=>o.setName("reason").setDescription("Reason").setRequired(true))).addSubcommand(s=>s.setName("interview").setDescription("Interview").addIntegerOption(o=>o.setName("application").setDescription("Application ID").setRequired(true))).addSubcommand(s=>s.setName("hold").setDescription("Hold").addIntegerOption(o=>o.setName("application").setDescription("Application ID").setRequired(true))),
new SlashCommandBuilder().setName("hrcase").setDescription("Create HR case").setDefaultMemberPermissions(PermissionFlagsBits.Administrator).addUserOption(o=>o.setName("user").setDescription("Driver").setRequired(true)).addStringOption(o=>o.setName("type").setDescription("Type").setRequired(true)).addStringOption(o=>o.setName("reason").setDescription("Reason").setRequired(true)),
new SlashCommandBuilder().setName("loa").setDescription("Request leave of absence").addStringOption(o=>o.setName("start").setDescription("YYYY-MM-DD").setRequired(true)).addStringOption(o=>o.setName("return").setDescription("YYYY-MM-DD").setRequired(true)).addStringOption(o=>o.setName("reason").setDescription("Reason").setRequired(true)),
new SlashCommandBuilder().setName("trainingpass").setDescription("Record training pass").setDefaultMemberPermissions(PermissionFlagsBits.Administrator).addUserOption(o=>o.setName("user").setDescription("Driver").setRequired(true)).addStringOption(o=>o.setName("module").setDescription("Module").setRequired(true)).addStringOption(o=>o.setName("notes").setDescription("Notes").setRequired(false)),
new SlashCommandBuilder().setName("trainingfail").setDescription("Record training fail").setDefaultMemberPermissions(PermissionFlagsBits.Administrator).addUserOption(o=>o.setName("user").setDescription("Driver").setRequired(true)).addStringOption(o=>o.setName("module").setDescription("Module").setRequired(true)).addStringOption(o=>o.setName("notes").setDescription("Notes").setRequired(false)),
new SlashCommandBuilder().setName("convoycreate").setDescription("Create convoy").setDefaultMemberPermissions(PermissionFlagsBits.Administrator).addStringOption(o=>o.setName("name").setDescription("Name").setRequired(true)).addStringOption(o=>o.setName("date").setDescription("YYYY-MM-DD").setRequired(true)).addStringOption(o=>o.setName("departure").setDescription("Departure").setRequired(true)).addStringOption(o=>o.setName("destination").setDescription("Destination").setRequired(true)),
new SlashCommandBuilder().setName("companylive").setDescription("Show live Sterling Tracker sessions")
].map(c=>c.toJSON())}
export async function registerCommands(c){const r=new REST({version:"10"}).setToken(c.token);await r.put(Routes.applicationGuildCommands(c.applicationId,c.guildId),{body:commandData()});}
